name: CI

on: [push, workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      RELEASE_PACKAGE_NAME: DemoPkg
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
        
    - name: check go version
      run: go version

    - name: install gotestsum
      run: go get -u gotest.tools/gotestsum

    - name: unit test
      run: gotestsum --junitfile unit-tests.xml

    - name: Publish unit test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: '*.xml'
        report_individual_runs: "true"

    - name: build code
      run: go build main.go
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifact
        path: main

    - name: Docker Hub login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/janedockerrepo:${{ github.sha }}
      
    - name: scan code
      uses: Azure/container-scan@v0.1
      with:
        image-name: ${{ secrets.DOCKER_USERNAME }}/janedockerrepo:${{ github.sha }}

    - name: Push Docker Image to Registry
      run: docker push ${{ secrets.DOCKER_USERNAME }}/janedockerrepo:${{ github.sha }}
