name: CI

env:
  GIT_USERNAME: "DefectDojo release bot"
  GIT_EMAIL: "dojo-release-bot@users.noreply.github.com"
on: [push, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      RELEASE_PACKAGE_NAME: DemoPkg
    steps:
    - name: Clean Workspace
      uses: AutoModality/action-clean@v1.1.0

    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
        
    - name: check go version
      run: go version

    - name: Super-Linter
      uses: github/super-linter@v4.5.1
      env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GO: true
          VALIDATE_YAML: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_KUBERNETES_KUBEVAL: true

    - name: install gotestsum
      run: go get -u gotest.tools/gotestsum

    - name: unit test
      run: gotestsum --junitfile unit-tests.xml

    - name: Publish unit test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: '*.xml'
        report_individual_runs: "true"

    - name: build code
      run: go build main.go
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifact
        path: main

    - name: Docker Hub login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/janedockerrepo:${{ github.sha }}
      
    - name: scan code
      uses: Azure/container-scan@v0.1
      with:
        image-name: ${{ secrets.DOCKER_USERNAME }}/janedockerrepo:${{ github.sha }}

    - name: Push Docker Image to Registry
      run: docker push ${{ secrets.DOCKER_USERNAME }}/janedockerrepo:${{ github.sha }}
