name: CI

on: [push, workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1' # The Go version to download (if necessary) and use.
    - run: go version

    - name: unit test
      run: go test -v

    - name: build code
      run: go build main.go

    - uses: mr-smithers-excellent/docker-build-push@v5.5
      name: Build & push Docker image
      with:
        image: gojane20/janedockerrepo
        tags: v1
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        