name: CI

on: [push, workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1' # The Go version to download (if necessary) and use.
    - run: go version

    - name: install gotestsum
      run: go get -u gotest.tools/gotestsum

    - name: unit test
      run: gotestsum --junitfile unit-tests.xml

    - name: Publish unit test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: '*.xml'
        report_individual_runs: "true"

    - name: build code
      run: go build main.go
    # scan code
    - name: Docker Hub login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build . -t gojane20/janedockerrepo:v3

    - name: Push Docker Image to Registry
      run: docker push gojane20/janedockerrepo:v3
