name: CI

on: [push, workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1' # The Go version to download (if necessary) and use.
    - run: go version

    - name: unit test
      run: go test -v

    - name: build code
      run: go build main.go

    - name: Login Docker
      uses: Azure/docker-login@v1
      with:
        login-server: index.docker.io # default: index.docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - run: |
        docker build . -t gojane20/demo:v1
        docker images
        docker push gojane20/demo:v1
